### ISSUE TITLE
Problem in  *label_list

### ISSUE THREAD

**Issue by lnj0532** [ljanyst/image-segmentation-fcn#1]
Very great work!  
When I run the codes with cityscapes dataset, a problem occured, at  line 136 in source_cityscapes.py
label_all  = np.dstack([label_bg, *label_list])
^SyntaxError: invalid syntax

How can i fix this problem? i appreciate your reply.

**Comment by ljanyst** [comment]
Which version of Python are you using?

**Comment by lnj0532** [comment]
Thanks for your reply.
The version of python I used is python 2.7.  I have solved this problem by replacing this line with a loop.

**Comment by ljanyst** [comment]
All this has been written and tested with python 3.5 in mind.

**Comment by lnj0532** [comment]
Many thanks!
