### ISSUE TITLE
regarding enableing your code to handle different image size 

### ISSUE THREAD

**Issue by surfreta** [ljanyst/image-segmentation-fcn#3]
Hello Lukasz,

It is very nice to see your code. I have a question,  if the training images are of different size, what kind of modifications that I have to make on your code? Thanks a lot.

**Comment by ljanyst** [comment]
As I have mentioned in the README, look into the source data source definitions (ie. https://github.com/ljanyst/image-segmentation-fcn/blob/master/source_cityscapes.py#L75) and search for `image_size`.
