### ISSUE TITLE
Retrain model from checkpoint

### ISSUE THREAD

**Issue by nomercy89** [ljanyst/image-segmentation-fcn#8]
Hello,
i want retrain my model from a checkpoint.
So, starting from train.py file, instead of calling the **build_from_vgg** function, i called **build_from_metagraph** function (passing to the function last checkpoint) , then i called net.get_optimizer(labels) and in the function i changed the variable self.numclasses with a number with number of classes (in my case is 2).

When i run my code I get this exception:
`ValueError: Duplicate node name in graph: 'optimizer/conv1_1/filter/Adam'`
when the line `optimizer = optimizer.minimize(loss)` is called in fcnvgg.py file.

Could you help me pls?

**Comment by ljanyst** [comment]
You're creating another optimizer this way. You need to find a way to get the optimizer tensor by name, just like in the case of the other tensors in `build_from_metagraph`.
